### ISSUE TITLE
Emergo: pieces get displayed as black rectangles (or not at all)

### ISSUE THREAD

**Issue by Soolost** [david-pfx/AmzPlayer#1]
In Emergo (zrf zip attached: [Emergo.zip](https://github.com/david-pfx/AmzPlayer/files/6949142/Emergo.zip)) just small black rectangles are shown instead of the proper images for each player.
Also: nothing shown on grids that have 3 dimensions (or for some other reason).

Attached is an AMZ image showing the issue after 2 moves played: 
![AMZ Emergo (2) Screen Shot 2021-08-07](https://user-images.githubusercontent.com/88584129/128601535-f4b00396-d1a0-4926-b366-bf9d9ed125f4.png)

And here's the ZoG image to show what it should look like: 
![ZoG Emergo Screen Shot 2021-08-07](https://user-images.githubusercontent.com/88584129/128601583-f4b0f6d8-e2c0-4356-8e50-fd8b02891a38.png)

Technically, each perceived disk is comprised of several different pieces (inside the zrf) that are put 'on top of' each other. To accomplish that, there are several (overlapping) grids, some of which have 3 dimensions. I.o.w. a lot of trickery to get the 3D effect.
It seems only the bottom grid is shown (the black bars), although there are a couple of dashes above it that may be an indication of other pieces on the other grid(-layers).

Even though Emergo may be too complicated to get the proper display, the same problem (a blacked out piece) occurs in Vexed which is straightforward as far as positioning pieces is concerned - all but one are shown properly. See the issue on Vexed (which concerns another matter) for a screenshot.

**Comment by Soolost** [comment]
Graphics update: the bars have gotten their color back. (the piece bmp files were wrong somehow; another "Save as..." of those fixed that)

Issue remaining: only the 'bottom' quarter of each disk is properly shown. The other three parts are cropped to show only their top pixel row (looks like little dashes).
Probably due to overlapping grids and the order in which they are drawn. Which is not a documented feature of ZoG, so low/no priority.

Anyway, here's a screen of the current state of things:

![AMZ Emergo (3 - black holes gone) Screen Shot 2021-08-10](https://user-images.githubusercontent.com/88584129/128898399-2c1ebb7e-773f-411d-859c-fe27b1d17a63.png)

**Comment by david-pfx** [comment]
This seems to be a scaling problem, when the size of the piece does not match the size of the position. Also when either the piece or position is not square. Working on it.

**Comment by david-pfx** [comment]
Fixed.  Tile display now calculates size correctly if piece non-square or smaller than position. Also fixes display for Tower of Hanoi puzzle.

**Comment by david-pfx** [comment]
Fixed 2: A dummy position with no location must not be displayed.

**Comment by Soolost** [comment]
> Fixed 2: A dummy position with no location must not be displayed.

Definitely not.
Even stronger, the Zillions Language Reference says: "Dummy positions never display a notation label and **any piece on a dummy position is not drawn**."

**Comment by david-pfx** [comment]
Closed release 21h13
