### ISSUE TITLE
Vexed: "Failed to transmit data"

### ISSUE THREAD

**Issue by Soolost** [david-pfx/AmzPlayer#2]
Regarding [Vexed.zip](https://github.com/david-pfx/AmzPlayer/files/6949185/Vexed.zip):
(pick "Vexed - Classic.zrf" along with "Vexed-Core.inc" if you want to try it)

On doing the housekeeping after the first move (e6-f6) “A major failure has occurred.” (after a while)
See screenshot:
![AMZ Vexed Screen Shot 2021-08-07](https://user-images.githubusercontent.com/88584129/128602507-e14b8867-92fb-4f79-84ad-210a064b0aed.png)

Note this happens when “?Helper is thinking…”, a random player that does the housekeeping in this solitaire game.

Console log (after quitting AMZ), which is abracadabra to me:
[AMZ Vexed Console log 2021-08-07.txt](https://github.com/david-pfx/AmzPlayer/files/6949195/AMZ.Vexed.Console.log.2021-08-07.txt)

---

(There was also the blacked out pieces problem (see issue #1 regarding Emergo).
The black rectangles in the 'Moves' and 'Par' indicators should be plain grey/blank ones.
Edit: This was resolved by re-saving the one rogue bmp file.)

**Comment by david-pfx** [comment]
This line says the engine died with a pointer fault. The rest of the log is the exception handler.

> Fatal error. 0xC0000005

 Coding bug. Will fix.

**Comment by david-pfx** [comment]
Fixed 1: A dummy player with no player images caused a crash.
Fixed 2: Zillions tries to animate moves to/from dummy positions, which caused a crash.

**Comment by Soolost** [comment]
Good catches! 

> Fixed 1: A dummy player with no player images caused a crash.

I assume you meant "A dummy piece ...".

> Fixed 2: Zillions tries to animate moves to/from dummy positions, which caused a crash.

Stupid Zillions ;-)

**Comment by david-pfx** [comment]
Sorry, I meant a piece that belongs to a dummy player may have no images defined for that player.

**Comment by david-pfx** [comment]
Closed release 21h13
