### ISSUE TITLE
Grand Chess: promotion choice unavailable

### ISSUE THREAD

**Issue by Soolost** [david-pfx/AmzPlayer#3]
Grand Chess comes with standard Zillions, as a variant of Fairy Chess. It's coded by Mark & Jeff.

In Grand Chess a pawn can (only) promote to any piece that has been captured by the opponent.
It can optionally promote when moving to the 8th or 9th rank, and it _must_ promote when moving to the 10th rank.
So usually there's a choice, and the choices can be different on every eligible move.

Unfortunately, AMZ doesn't present a way to choose and simply disallows moving, although the target square is indicated (by a circle) as a possibility. See, on hovering the mouse above J7:
![AMZ Grand Chess (3 hover) Screen Shot 2021-08-07](https://user-images.githubusercontent.com/88584129/128603301-56776c0e-3a27-4bd8-8c09-ee829fa7cf20.png)

Here's a screemshot without any hovering:
![AMZ Grand Chess (1) Screen Shot 2021-08-07](https://user-images.githubusercontent.com/88584129/128603362-aaae2b1b-3cdf-48b3-ab10-e8815091bbe2.png)

Note that the "Possible Moves" list clearly distinguishes between each (promotion) choice from J7. So, why not make that list clickable?
I'm sure that's easier said than done. But it would provide a way to play 'ambiguous' moves, in a generic manner (it'll work for every move in the list), without having a modal dialog.

I feel some way to choose is a must-have for a modern Zillions.
Even good old Chess needs it, promotion is to a bishop, knight, rook, or queen by player's choice! I made the issue about Grand Chess, because I forgot about Chess ;-).

**Comment by david-pfx** [comment]
Yes, ambiguous drag and drop moves are on my to-do list. And yes, a clickable list may well be a solution, but it's not really possible with so many moves on the open board before hovering over a piece. Anything to avoid going modal.

But meanwhile...

Did you notice the moves in the first screen are numbered, where the second are not? Pressing the number key will make that move. I guess I need to document that. [Doesn't work so well if there are more than 9...]

**Comment by Soolost** [comment]
No, I didn't notice, that's (almost) brilliant!
That resolves the issue with (Grand) Chess, but not in every case as you've noted.

Unfortunately, the list can be rather long - see this screenshot of HanniBall, hovering above the "White Lion-w-Ball":

![AMZ HanniBall Screen Shot 2021-08-08](https://user-images.githubusercontent.com/88584129/128635790-e49c5e22-79f0-4a12-bb7f-fc5598109e1a.png)

Here, all drag-n-drops (but one) are 'ambiguous', each with 4 different results.

If only, after a (drag and) drop, the list could be limited to only the moves that have the same target, I would be very happy. A caption like "Pick a number to move" may help.
Kinda modal, but it might be 'loosely modal'. 
Just some thoughts, I gladly leave it up to you. I do see the problem with my original suggestion.

**Comment by david-pfx** [comment]
Latest release includes support for ambiguous drag and drop.

If this does not fix the problem, please reopen and supply a saved game.
