### ISSUE TITLE
Go-Moku (from ZoG v2): Game error on first drop

### ISSUE THREAD

**Issue by Soolost** [david-pfx/AmzPlayer#4]
Go-Moku included with AMZ (and ZoG v3) fails to load with a parser error.
It looks like it uses something new that isn’t recognised. As opposed to an old thing not being handled properly. 
 
So, I thought Go-Moku.zrf from ZoG v2 would run fine. 
(zrf: [Go-Moku.zrf.txt](https://github.com/david-pfx/AmzPlayer/files/6954495/Go-Moku.zrf.txt) - remove txt extension and put in Rules folder) 
It loads okay, but fails on the first drop (without anything on the console):

![AMZ Go-Moku v2 Screen Shot 2021-08-08](https://user-images.githubusercontent.com/88584129/128706030-5cbc0df3-acfa-4d58-b00f-a437499d08c1.png)

**Comment by david-pfx** [comment]
Error due to reliance on different image files.

Works correctly with the v2 release including image files.
